---
abstract: 'boost productivity by blocking distracting websites'
author:
  - 'Richard Harris <RJH@cpan.org>'
build_requires:
  File::Temp: 0
  Socket: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-GSD
requires:
  Carp: 0
  English: 0
  File::ShareDir: 0
  File::Slurp: 0
  Getopt::Long: 0
  IPC::System::Simple: 0
  Pod::Usage: 0
  YAML: 0
  autodie: 0
  perl: 5.006
  strict: 0
  warnings: 0
version: 0.4
